In [48]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split

import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
import tensorflow as tf
from tensorflow.keras import backend as k

In [51]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split


In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [53]:
from tensorflow.keras import models

In [54]:
#import required libraries

#import pandas library
import pandas as pd
#import numpy
import numpy as np
#import requests
import requests
#import io
import io
import os

In [55]:
#from google.colab import drive
#drive.mount('/content/drive')

In [56]:
#import the dataset in the data variable
data=pd.read_csv("kindle_reviews.csv")

In [57]:
data.shape

(982619, 10)

In [58]:
data.head()

Unnamed: 0        asin helpful  overall  \
0           0  B000F83SZQ  [0, 0]        5   
1           1  B000F83SZQ  [2, 2]        4   
2           2  B000F83SZQ  [2, 2]        4   
3           3  B000F83SZQ  [1, 1]        5   
4           4  B000F83SZQ  [0, 1]        4   

                                          reviewText   reviewTime  \
0  I enjoy vintage books and movies so I enjoyed ...   05 5, 2014   
1  This book is a reissue of an old one; the auth...   01 6, 2014   
2  This was a fairly interesting read.  It had ol...   04 4, 2014   
3  I'd never read any of the Amy Brewster mysteri...  02 19, 2014   
4  If you like period pieces - clothing, lingo, y...  03 19, 2014   

       reviewerID                         reviewerName             summary  \
0  A1F6404F1VG29J                           Avidreader  Nice vintage story   
1   AN0N05A9LIJEQ                             critters        Different...   
2   A795DMNCJILA6                                  dot               Oldie   
3  A1FV0SX13TWVXQ  Elaine H. Turley "Montana Songbird"  I really liked it.   
4  A3SPTOKDG7WBLN                   Father Dowling Fan      Period Mystery   

   unixReviewTime  
0      1399248000  
1      1388966400  
2      1396569600  
3      1392768000  
4      1395187200

In [59]:
#assigning 50000 rows to data
data=data.head(50000)

In [60]:
#checking for null values
data.isnull().any()

Unnamed: 0        False
asin              False
helpful           False
overall           False
reviewText         True
reviewTime        False
reviewerID        False
reviewerName       True
summary           False
unixReviewTime    False
dtype: bool

In [61]:
data.isnull().sum()

Unnamed: 0          0
asin                0
helpful             0
overall             0
reviewText          1
reviewTime          0
reviewerID          0
reviewerName      149
summary             0
unixReviewTime      0
dtype: int64

In [62]:
#deleting or dropping the unwanted columns from the dataset
del data['Unnamed: 0']
del data['asin']
del data['helpful']
del data['reviewTime']
del data['reviewerID']
del data['reviewerName']
del data['unixReviewTime']

In [63]:
#first 10 rows of data
data.head(10)

overall                                         reviewText  \
0        5  I enjoy vintage books and movies so I enjoyed ...   
1        4  This book is a reissue of an old one; the auth...   
2        4  This was a fairly interesting read.  It had ol...   
3        5  I'd never read any of the Amy Brewster mysteri...   
4        4  If you like period pieces - clothing, lingo, y...   
5        4  A beautiful in-depth character description mak...   
6        4  I enjoyed this one tho I'm not sure why it's c...   
7        4  Never heard of Amy Brewster. But I don't need ...   
8        5  Darth Maul working under cloak of darkness com...   
9        4  This is a short story focused on Darth Maul's ...   

                                         summary  
0                             Nice vintage story  
1                                   Different...  
2                                          Oldie  
3                             I really liked it.  
4                                 Period Mystery  
5                                         Review  
6                       Nice old fashioned story  
7  Enjoyable reading and reminding the old times  
8                                     Darth Maul  
9                       Not bad, not exceptional

In [64]:
#checking value counts
data.overall.value_counts()

5    23090
4    14980
3     7013
2     2832
1     2085
Name: overall, dtype: int64

In [65]:
#check the null values
data.isna().sum()

overall       0
reviewText    1
summary       0
dtype: int64

In [66]:
#joining review description and summary into one col
data['reviewText']=data['reviewText']+" "+data['summary']

In [67]:
data.head()

overall                                         reviewText  \
0        5  I enjoy vintage books and movies so I enjoyed ...   
1        4  This book is a reissue of an old one; the auth...   
2        4  This was a fairly interesting read.  It had ol...   
3        5  I'd never read any of the Amy Brewster mysteri...   
4        4  If you like period pieces - clothing, lingo, y...   

              summary  
0  Nice vintage story  
1        Different...  
2               Oldie  
3  I really liked it.  
4      Period Mystery

In [68]:
data.drop(['summary'],axis=1,inplace=True)

In [69]:
#checking for null values
data.isna().sum()

overall       0
reviewText    1
dtype: int64

In [70]:
#since there is only one null value, replace it with blank space
data['reviewText'].fillna("",inplace = True)

In [71]:
#Grouping the overall rating of scale 1-5 to 2 categories
def review_sentiment(rating):
    #0(positive) and  with 1(negative) 
    if(rating == 5 or rating == 4 or rating==3):
        return 0
    else:
        return 1

In [72]:
data.overall = data.overall.apply(review_sentiment)

In [73]:
data.overall.value_counts()

0    45083
1     4917
Name: overall, dtype: int64

In [74]:
data.head(50)

overall                                         reviewText
0         0  I enjoy vintage books and movies so I enjoyed ...
1         0  This book is a reissue of an old one; the auth...
2         0  This was a fairly interesting read.  It had ol...
3         0  I'd never read any of the Amy Brewster mysteri...
4         0  If you like period pieces - clothing, lingo, y...
5         0  A beautiful in-depth character description mak...
6         0  I enjoyed this one tho I'm not sure why it's c...
7         0  Never heard of Amy Brewster. But I don't need ...
8         0  Darth Maul working under cloak of darkness com...
9         0  This is a short story focused on Darth Maul's ...
10        0  I think I have this one in both book and audio...
11        0  Title has nothing to do with the story.  I did...
12        0  Well written. Interesting to see Sideous (thro...
13        0  Troy Denning's novella Recovery was originally...
14        0  I am not for sure on how much of a difference ...
15        0  I really enjoyed the book. Had the normal back...
16        0  Great read enjoyed every minute of it .  I thi...
17        0  Another well written eBook by Troy Denning, bu...
18        0  This one promises to be another good book. I h...
19        0  I have a version of "Star by Star" that does n...
20        0  Excellent! Very well written story, very excit...
21        1  With Ylesia, a novella originally published in...
22        0  Great book couldn't put it down.  The story ex...
23        0  Most of the New Jedi Order books focus on the ...
24        0  I was hoping to find this one in book form. Th...
25        0  The events of "Ylesia" take place during "Dest...
26        0  Really shouldn't have Han Solo on the cover as...
27        0  Originally published as an e-book coinciding w...
28        0  This book was a good idea. I have always wante...
29        0  Great short story. It gives a little more insi...
30        0  I love anything with Chewbacca in it.  Him and...
31        0  A great little chapter to read on my Kindle, b...
32        0  I love the stories with Chewie in them! this e...
33        0  I'm not really sure where it actually fits int...
34        0  I really do enjoy Troy Denning's work, I want ...
35        0  Timothy Zahn's Fool's Bargain is a short story...
36        0  Not too bad, an intro-short-story for some big...
37        0  I absolutely love this book. Though it is shor...
38        0  What can I say Stormtroopers.  A story with tr...
39        1  For whatever reason, Star Wars short stories a...
40        0  As an ebook it reads very well on my Kindle, b...
41        0  ** Note: this story appears as a bonus in the ...
42        1  I admit it, I snapped this up the moment I saw...
43        0  I love Timothy Zahn's work!  He does what no o...
44        0  The hero in this story has been living in NYC ...
45        0  The Iron Marshall, by Louie L`Amour is one of ...
46        0  This is yet another  L'Amour winner. I have ye...
47        0  I almost didn't get this book because of the c...
48        0  This story by Louis L'Amour was the very first...
49        0  This is how it was in the big gambling and cor...

In [75]:
len(list(data['overall']))

50000

In [76]:
x=data.iloc[:,1].values

In [77]:
#import natural language toolkit
#import nltk
#nltk.download("stopwords")
#nltk.download("wordnet")
#import stopwords library to remove stopwords
#from nltk.corpus import stopwords
#library used for stem the words
#from nltk.stem.porter import PorterStemmer
#create an object for stemming
#ps = PorterStemmer()
#library used for stem the words
#from nltk.stem import WordNetLemmatizer
#create an object for wordnet lemmatizer
#wordnet=WordNetLemmatizer()

In [78]:
import re

In [79]:
#pip install --user -U nltk

In [80]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [81]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [82]:
 # Initialize empty array to append clean text 
   #from nltk.stem import WordNetLemmatizer
    #corpus=[]
#from nltk.corpus import wordnet
    #from nltk.stem.wordnet import WordNetLemmatizer
corpus=[]
# no of rows to clean 
for i in range(len(x)):
    #replacing punctuations and numbers using re library 
    temp=re.sub('[^a-zA-Z]',' ',x[i])
    # convert all text to lower cases
    temp=temp.lower()
    # split to array(default delimiter is " ") 
    temp=temp.split()
    # creating WordNetLemmatizer object to take main lemma of each word
    from nltk.stem.wordnet import WordNetLemmatizer
    wordnet = WordNetLemmatizer()
    #loop for leammatization each word in string array at ith row 
    temp=[wordnet.lemmatize(word)for word in temp if not word in set(stopwords.words('english'))]
    #rejoin all string array elements to create back into a string 
    temp=' '.join(temp)
    #append each string to create array of clean text 
    corpus.append(temp)

In [83]:
#creating bag of word model
from sklearn.feature_extraction.text import CountVectorizer
#To extract max feature, "max_features" is attribute to 
#experiment with to get better results
cv=CountVectorizer(max_features= 6000)
#z contains vectorized data (independent variable) 
z=cv.fit_transform(corpus).toarray()

In [84]:
z.shape

(50000, 6000)

In [85]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"ibmamazon.save")

['ibmamazon.save']

In [86]:
y=data.iloc[:,0].values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(z,y,test_size=0.2,random_state=0)

In [88]:
x_train.shape

(40000, 6000)

In [89]:
x_test.shape

(10000, 6000)

In [90]:
z.shape

(50000, 6000)

In [91]:
#import libraries
import tensorflow
import keras
#import Sequential
from tensorflow.keras.models import Sequential
#import Dense
from tensorflow.keras.layers import Dense

In [92]:
#intialize the model
model=Sequential()

#adding input layer
model.add(Dense(600,kernel_initializer='random_uniform',
                activation='relu'))

#adding hidden layer
model.add(Dense(100,kernel_initializer='random_uniform',
                activation='relu'))

#adding output layer
model.add(Dense(1,kernel_initializer='random_uniform',
                activation='sigmoid'))

#configure the learning process
model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])

In [93]:
print(x_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [94]:
#training the model
model.fit(x_train,y_train,epochs=20,batch_size=32)

Epoch 1/20
1250/1250 [==============================] - 44s 30ms/step - loss: 0.2010 - accuracy: 0.9250
Epoch 2/20
1250/1250 [==============================] - 36s 29ms/step - loss: 0.1107 - accuracy: 0.9575
Epoch 3/20
1250/1250 [==============================] - 37s 30ms/step - loss: 0.0392 - accuracy: 0.9867
Epoch 4/20
1250/1250 [==============================] - 38s 30ms/step - loss: 0.0059 - accuracy: 0.9986
Epoch 5/20
1250/1250 [==============================] - 38s 30ms/step - loss: 0.0014 - accuracy: 0.9997
Epoch 6/20
1250/1250 [==============================] - 41s 33ms/step - loss: 4.0910e-04 - accuracy: 0.9999
Epoch 7/20
1250/1250 [==============================] - 36s 29ms/step - loss: 7.8451e-05 - accuracy: 1.0000
Epoch 8/20
1250/1250 [==============================] - 35s 28ms/step - loss: 8.2456e-06 - accuracy: 1.0000
Epoch 9/20
1250/1250 [==============================] - 34s 27ms/step - loss: 3.4967e-06 - accuracy: 1.0000
Epoch 10/20
1250/1250 [=========================

In [95]:
#save the model
model.save("amazonibm.h5")

In [96]:
ypred=model.predict(x_test)

In [97]:
ypred

array([[3.7939717e-35],
       [6.9901695e-28],
       [7.6669481e-30],
       ...,
       [0.0000000e+00],
       [0.0000000e+00],
       [1.8628883e-10]], dtype=float32)

In [98]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"ibmamazon.save")

['ibmamazon.save']

In [99]:
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('ibmamazon.save'))

In [105]:
d="Writing was good"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result>0.5
#print(prediction)
if prediction[0] == False:
    print("negative review")
elif prediction[0] == True:
    print("Positive review")


[[5.0325293e-06]]
negative review


In [106]:
from tensorflow.keras.models import load_model
model=tensorflow.keras.models.load_model("amazonibm.h5")

In [107]:
#import load_model function
from tensorflow.keras.models import load_model
#load our saved model file
model=tensorflow.keras.models.load_model("amazonibm.h5")
#import countvecorizer
from sklearn.feature_extraction.text import CountVectorizer
import joblib
#load saved bag of word model file
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('ibmamazon.save'))

In [109]:
d="good with application"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result>0.5
#print(prediction)
if prediction[0] == False:
    print("negative review")
elif prediction[1] == True:
    print("Negative review")

[[1.5839889e-10]]
negative review
